/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogComputeSdkVsAgentosRouteImport } from './routes/blog.compute-sdk-vs-agentos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogComputeSdkVsAgentosRoute = BlogComputeSdkVsAgentosRouteImport.update({
  id: '/blog/compute-sdk-vs-agentos',
  path: '/blog/compute-sdk-vs-agentos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/compute-sdk-vs-agentos': typeof BlogComputeSdkVsAgentosRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/compute-sdk-vs-agentos': typeof BlogComputeSdkVsAgentosRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/compute-sdk-vs-agentos': typeof BlogComputeSdkVsAgentosRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog/compute-sdk-vs-agentos' | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/compute-sdk-vs-agentos' | '/blog'
  id: '__root__' | '/' | '/blog/compute-sdk-vs-agentos' | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogComputeSdkVsAgentosRoute: typeof BlogComputeSdkVsAgentosRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/compute-sdk-vs-agentos': {
      id: '/blog/compute-sdk-vs-agentos'
      path: '/blog/compute-sdk-vs-agentos'
      fullPath: '/blog/compute-sdk-vs-agentos'
      preLoaderRoute: typeof BlogComputeSdkVsAgentosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogComputeSdkVsAgentosRoute: BlogComputeSdkVsAgentosRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
